
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[193] =
    {   0,
        0,    2,    0,    0,    0,    0,    0,    0,    0,    0,
       96,   94,    4,    1,   49,   73,   30,   44,   58,   50,
       51,   32,   28,   56,   29,   94,   31,   22,   57,   35,
       41,   37,   21,   54,   55,   46,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   52,   45,   53,    2,
       72,   71,   60,   70,   60,   85,   76,   85,   84,   85,
       89,   95,   89,   89,   93,   91,   93,    4,   40,   42,
       33,   34,   24,   90,   86,    0,   22,   23,   47,   36,
       39,   38,   48,   21,   21,   21,   21,   21,   21,    9,
       21,   21,   21,    5,   21,   21,   21,   21,   21,   43,

        2,    3,   59,   59,   69,   64,   67,   65,   62,   66,
       63,   68,   61,   76,   77,   83,   78,   81,   79,   80,
       77,   82,   75,    0,   74,   88,   87,    0,   92,   24,
       23,    0,   23,   23,    0,   23,   21,   21,   21,   21,
       21,   21,   21,   21,    7,   11,   21,   21,   21,   21,
       24,   24,    0,   23,   27,   26,   21,   18,   12,   21,
       21,   21,    6,   21,   21,   21,   15,   21,    0,   23,
       23,   27,   10,   21,   21,   21,   13,   21,   21,    8,
       25,   21,   21,   14,   16,   17,   25,   25,   21,   19,
       20,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   26,    1,   32,   33,   34,   35,

       36,   37,   26,   38,   39,   26,   40,   41,   26,   42,
       43,   26,   26,   44,   45,   46,   47,   48,   49,   26,
       26,   26,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    3,
        3,    1,    1,    1,    1,    4,    4,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[200] =
    {   0,
        0,  299,   50,   51,   52,   60,   61,   64,   68,   69,
      300,  302,   71,  302,  275,  302,  302,  288,  302,  302,
      302,  302,  282,  302,  279,   64,   72,   74,  302,   64,
      271,   72,    0,  302,  302,  302,  250,   66,   63,  252,
       59,   66,  256,  242,  247,  251,  302,  237,  302,  109,
      302,  302,  108,  302,  258,  302,  302,  283,  149,  115,
      302,  302,  282,  102,  302,  302,  265,  120,  302,  302,
      302,  302,  110,  302,  302,  112,  140,  153,  302,  302,
      302,  302,  302,    0,  247,  237,  249,  238,  242,  231,
      232,  233,  231,    0,  228,  227,  233,  232,  231,  302,

      160,  173,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      302,  302,  302,  266,  302,  302,  302,  265,  302,  127,
      167,    0,  181,  118,  114,  171,  235,  207,  195,  186,
      198,  196,  189,  186,    0,    0,  162,  154,  155,  139,
      163,  184,  186,  193,  191,  195,  132,    0,    0,  124,
      112,  114,    0,  107,  107,  115,    0,  107,  199,  201,
      203,  207,    0,   87,   86,   85,    0,   75,   74,    0,
      216,   31,   28,    0,    0,    0,  220,  224,   34,    0,
        0,  302,  245,  249,  253,  257,  259,  262,   52

    } ;

static const flex_int16_t yy_def[200] =
    {   0,
      192,    1,  193,  193,  194,  194,  195,  195,  196,  196,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  197,  192,  192,  192,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  192,  192,  192,  192,
      192,  192,  192,  192,   53,  192,  192,  192,  192,   59,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  198,  192,  192,  192,
      192,  192,  192,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  192,

      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  199,  199,  192,  192,  192,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      192,  192,  192,  192,  199,  192,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  192,  192,
      192,  192,  197,  197,  197,  197,  197,  197,  197,  197,
      192,  197,  197,  197,  197,  197,  192,  192,  197,  197,
      197,    0,  192,  192,  192,  192,  192,  192,  192

    } ;

static const flex_int16_t yy_nxt[355] =
    {   0,
       12,   13,   14,   13,   13,   13,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   33,   34,   12,   35,
       36,   33,   37,   38,   39,   40,   41,   33,   42,   33,
       33,   33,   33,   43,   44,   33,   33,   45,   46,   47,
       48,   49,   52,   52,   57,  155,   58,   53,   53,   59,
       54,   54,   57,   62,   58,   63,   62,   59,   63,  191,
       66,   66,   68,  190,   68,   68,   68,  189,   55,   55,
       60,   67,   67,   73,   73,   74,   79,   80,   60,   64,
       75,   76,   64,   77,   77,   82,   83,   86,   89,   92,

       78,   93,   94,   87,  127,   90,  128,   95,   88,   78,
      101,  186,   68,   68,  102,  103,  185,  123,  104,  124,
      184,   68,  125,   68,   68,   68,  183,  105,  182,   73,
       73,  131,  131,  156,  156,  135,  130,  136,  136,  106,
      107,  151,  180,  151,  108,  130,  152,  152,  179,  109,
      178,  110,  177,  111,  176,  112,  115,   76,  175,   77,
       77,  101,  174,   68,   68,  102,  133,  134,  116,  134,
      135,  173,  136,  136,   68,  133,   68,   68,   68,  168,
      117,  118,  152,  152,  153,  119,  131,  131,  135,  167,
      136,  136,  120,  154,  121,  134,  122,  134,  135,  166,

      136,  136,  154,  152,  152,  169,  169,  170,  165,  170,
      172,  172,  171,  171,  156,  156,  153,  164,  169,  169,
      171,  171,  171,  171,  163,  181,  172,  172,  162,  161,
      187,  160,  187,  135,  181,  188,  188,  135,  159,  188,
      188,  135,  158,  188,  188,   51,   51,   51,   51,   56,
       56,   56,   56,   61,   61,   61,   61,   65,   65,   65,
       65,   84,   84,  132,  132,  132,  157,  127,  123,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  129,  126,  114,  113,  100,   99,   98,
       97,   96,   91,   85,   81,   72,   71,   70,   69,  192,

       50,   11,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192
    } ;

static const flex_int16_t yy_chk[355] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,  199,    5,    3,    4,    5,
        3,    4,    6,    7,    6,    7,    8,    6,    8,  189,
        9,   10,   13,  183,   13,   13,   13,  182,    3,    4,
        5,    9,   10,   26,   26,   27,   30,   30,    6,    7,
       27,   28,    8,   28,   28,   32,   32,   38,   39,   41,

       28,   41,   42,   38,   64,   39,   64,   42,   38,   28,
       50,  179,   50,   50,   50,   53,  178,   60,   53,   60,
      176,   68,   60,   68,   68,   68,  175,   53,  174,   73,
       73,   76,   76,  135,  135,  134,   73,  134,  134,   53,
       53,  130,  168,  130,   53,   73,  130,  130,  166,   53,
      165,   53,  164,   53,  162,   53,   59,   77,  161,   77,
       77,  101,  160,  101,  101,  101,   77,   78,   59,   78,
       78,  157,   78,   78,  102,   77,  102,  102,  102,  150,
       59,   59,  151,  151,  131,   59,  131,  131,  136,  149,
      136,  136,   59,  131,   59,  133,   59,  133,  133,  148,

      133,  133,  131,  152,  152,  153,  153,  154,  147,  154,
      155,  155,  154,  154,  156,  156,  169,  144,  169,  169,
      170,  170,  171,  171,  143,  169,  172,  172,  142,  141,
      181,  140,  181,  181,  169,  181,  181,  187,  139,  187,
      187,  188,  138,  188,  188,  193,  193,  193,  193,  194,
      194,  194,  194,  195,  195,  195,  195,  196,  196,  196,
      196,  197,  197,  198,  198,  198,  137,  128,  124,   99,
       98,   97,   96,   95,   93,   92,   91,   90,   89,   88,
       87,   86,   85,   67,   63,   58,   55,   48,   46,   45,
       44,   43,   40,   37,   31,   25,   23,   18,   15,   11,

        2,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2005110.l"
#line 6 "2005110.l"
#include<bits/stdc++.h>
#include<iostream>
#include "2005110.h"
#include "y.tab.h"


using namespace std ;

extern YYSTYPE yylval;

void yyerror(char *);

ofstream logout;
ofstream tokenout;

int lineCount = 1;
int errCount = 0;
int warningCount = 0;
int start =0;
int indentationCount = 0;
int spaceCount = 0;

string inputChar = "";
string inputString = "";
bool multiLineString =  false;
string token = "";

SymbolTable table(10);

void printToken(string token , string lexeme , int lineNum)
{
	//tokenout << "<" << token <<", " << lexeme << ">" << endl ;
	logout << "Line# "<< lineNum <<": Token <" << token << "> Lexeme " << lexeme << " found" << endl; 
}



#line 626 "lex.yy.c"

#line 628 "lex.yy.c"

#define INITIAL 0
#define ESCAPED_CHAR_STATE 1
#define STRING_STATE 2
#define SINGLE_COMMENT_STATE 3
#define MULTI_LINE_COMMENT_STATE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 60 "2005110.l"



#line 856 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 193 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 302 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 63 "2005110.l"
{
			lineCount++;
		
			spaceCount = 0;
		  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "2005110.l"
{
			spaceCount = yyleng;
			
			if(spaceCount == 0)
			{
				logout << "Line# " <<lineCount << ": warning, " << indentationCount <<" of tabs needed but got 0 tabs." << endl;
				warningCount++;
				spaceCount = 0;
			}

			else if(spaceCount != indentationCount)
			{
				logout << "Line# " << lineCount << ": warning, " << indentationCount << " of tabs needed but got " << spaceCount << " tabs." << endl;
				warningCount++;
				spaceCount = 0;
			}

}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "2005110.l"
{
				logout << "Line# " << lineCount << ": Warning, tab requrired but got space." << endl;
				warningCount++;
				spaceCount = 0;
               }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 97 "2005110.l"
{

			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 103 "2005110.l"
{
				printToken("IF" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "IF");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return IF;
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 114 "2005110.l"
{	
				printToken("ELSE" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "ELSE");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return ELSE;
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "2005110.l"
{	
				printToken("FOR" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "FOR");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return FOR;
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "2005110.l"
{	
				printToken("WHILE" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "WHILE");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return WHILE;
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 147 "2005110.l"
{
				printToken("DO" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "DO");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return DO;
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 158 "2005110.l"
{	
				printToken("BREAK" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "BREAK");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return BREAK;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 169 "2005110.l"
{	
				printToken("INT" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "INT");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return INT;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 180 "2005110.l"
{	
				printToken("CHAR" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "CHAR");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return CHAR;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 191 "2005110.l"
{
				printToken("FLOAT" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "FLOAT");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return FLOAT;
            }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 202 "2005110.l"
{
				printToken("DOUBLE" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "DOUBLE");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo  = symbolInfo;
                return DOUBLE;
            }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 213 "2005110.l"
{
				printToken("VOID" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "VOID");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return VOID;
            }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 224 "2005110.l"
{
				printToken("RETURN" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "RETURN");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return RETURN;
            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 235 "2005110.l"
{
				printToken("SWITCH" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "SWITCH");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return SWITCH;
            }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 246 "2005110.l"
{
				printToken("CASE" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "CASE");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return CASE;
            }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 257 "2005110.l"
{
				printToken("DEFAULT" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "DEFAULT");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo  =  symbolInfo;
                return DEFAULT;
            }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 268 "2005110.l"
{
				printToken("CONTINUE" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "CONTINUE");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return CONTINUE;
            }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 282 "2005110.l"
{
									printToken("ID" , yytext , lineCount);

									SymbolInfo* symbolInfo = new SymbolInfo( yytext , "ID");
                                    symbolInfo->setStartLine(lineCount);
                                    symbolInfo->setEndLine(lineCount);
                                    symbolInfo->setIsLeaf(true);
                                    yylval.symbolInfo  = symbolInfo;
							
				                    return ID;
								}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 297 "2005110.l"
{
										printToken("CONST_INT" , yytext , lineCount);

                                        SymbolInfo* symbolInfo = new SymbolInfo( yytext , "CONST_INT");
                                        symbolInfo->setStartLine(lineCount);
                                        symbolInfo->setEndLine(lineCount);
                                        symbolInfo->setIsLeaf(true);
                                        yylval.symbolInfo  = symbolInfo;
                                        return CONST_INT;
            						}
	YY_BREAK
case 23:
#line 310 "2005110.l"
case 24:
YY_RULE_SETUP
#line 311 "2005110.l"
{
										printToken("CONST_FLOAT" , yytext , lineCount);

                                        SymbolInfo* symbolInfo = new SymbolInfo( yytext , "CONST_FLOAT");
                                        symbolInfo->setStartLine(lineCount);
                                        symbolInfo->setEndLine(lineCount);
                                        symbolInfo->setIsLeaf(true);
                                        yylval.symbolInfo = symbolInfo;
                                        return CONST_FLOAT;
                        			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 323 "2005110.l"
{
													logout << "Error at line# " << lineCount << ": TOO_MANY_DECIMAL_POINTS " << yytext << endl;
													errCount++;
										  		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 329 "2005110.l"
{
																	logout << "Error at line# " << lineCount << ": ILLFORMED_NUMBER " << yytext << endl;
																	errCount++;
																}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 335 "2005110.l"
{
											string input = yytext;
											logout << "Error at line# " << lineCount << ": INVALID_ID_SUFFIX_NUM_PREFIX " << yytext << endl;
											errCount++;
										}
	YY_BREAK
case 28:
#line 344 "2005110.l"
case 29:
YY_RULE_SETUP
#line 344 "2005110.l"
{
				printToken("ADDOP" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "ADDOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return ADDOP;
            }
	YY_BREAK
case 30:
#line 356 "2005110.l"
case 31:
#line 357 "2005110.l"
case 32:
YY_RULE_SETUP
#line 357 "2005110.l"
{	
				printToken("MULOP" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "MULOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return MULOP;
            }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 370 "2005110.l"
{
				printToken("INCOP" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "INCOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return INCOP;
            }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 381 "2005110.l"
{
                printToken("DECOP" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "DECOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo  = symbolInfo;
                return DECOP;
            }
	YY_BREAK
case 35:
#line 394 "2005110.l"
case 36:
#line 395 "2005110.l"
case 37:
#line 396 "2005110.l"
case 38:
#line 397 "2005110.l"
case 39:
#line 398 "2005110.l"
case 40:
YY_RULE_SETUP
#line 398 "2005110.l"
{	
				printToken("RELOP" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "RELOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo =  symbolInfo;
                return RELOP;

            }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 411 "2005110.l"
{
				printToken("ASSIGNOP" , yytext , lineCount);


                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "ASSIGNOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo =  symbolInfo;
                return ASSIGNOP;

            }
	YY_BREAK
case 42:
#line 426 "2005110.l"
case 43:
YY_RULE_SETUP
#line 426 "2005110.l"
{	
				printToken("LOGICOP" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "LOGICOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return LOGICOP;
            }
	YY_BREAK
case 44:
#line 439 "2005110.l"
case 45:
#line 440 "2005110.l"
case 46:
#line 441 "2005110.l"
case 47:
#line 442 "2005110.l"
case 48:
YY_RULE_SETUP
#line 442 "2005110.l"
{
				printToken("BITOP" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "BITOP");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return BITOP;

            }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 455 "2005110.l"
{	
				printToken("NOT" , yytext , lineCount);


                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "NOT");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return NOT;
        	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 468 "2005110.l"
{
				printToken("LPAREN" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "LPAREN");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return LPAREN;
            }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 480 "2005110.l"
{
				printToken("RPAREN" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "RPAREN");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return RPAREN;

            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 493 "2005110.l"
{
				indentationCount++;
				table.EnterScope();

				printToken("LCURL" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "LCURL");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return LCURL;

            }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 509 "2005110.l"
{
				--indentationCount;
				//table.ExitScope();

				printToken("RCURL" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "RCURL");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo  = symbolInfo;
                return RCURL;

            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 524 "2005110.l"
{
				printToken("LSQUARE" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "LSQUARE");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return LSQUARE;
            }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 536 "2005110.l"
{
				printToken("RSQUARE" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "RSQUARE");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return RSQUARE;
            }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 548 "2005110.l"
{
				printToken("COMMA" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "COMMA");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo  = symbolInfo;
                return COMMA;

			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 561 "2005110.l"
{
				printToken("SEMICOLON" , yytext , lineCount);

                SymbolInfo* symbolInfo = new SymbolInfo( yytext , "SEMICOLON");
                symbolInfo->setStartLine(lineCount);
                symbolInfo->setEndLine(lineCount);
                symbolInfo->setIsLeaf(true);
                yylval.symbolInfo = symbolInfo;
                return SEMICOLON;
            }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 576 "2005110.l"
{
    				BEGIN(ESCAPED_CHAR_STATE);
				}			
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 581 "2005110.l"
{
										inputChar += "\\'";
									}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 586 "2005110.l"
{
										inputChar += "\\";
										inputChar += '\"';
									}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 592 "2005110.l"
{
										inputChar += "\\";
										inputChar += "\\";
									}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 598 "2005110.l"
{
										inputChar += "\n";
									}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 603 "2005110.l"
{
										inputChar += "\t";
									}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 608 "2005110.l"
{
										inputChar += "\a";
									}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 613 "2005110.l"
{
										inputChar += "\f";
									}							
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 618 "2005110.l"
{
										inputChar += "\r";
									}					
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 623 "2005110.l"
{
										inputChar += "\b";
									}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 628 "2005110.l"
{
										inputChar += "\v";
									}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 633 "2005110.l"
{
										inputChar += "\0";
									}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 637 "2005110.l"
{
										if(inputChar.size()==0)
										{
											logout << "Error at line# " << lineCount << ": EMPTY_CONST_CHAR ''" << endl;
											errCount++;
										}
										else if(inputChar.size()==1 || (inputChar.size()==2 &&  inputChar[0] == '\\'))
										{
											printToken("CONST_CHAR" , inputChar , lineCount);
										}
										else
										{	
											string outputChar = "'";
											outputChar += inputChar;
											outputChar += "'";

											logout << "Error at line# " << lineCount << ": MULTICHAR_CONST_CHAR " << outputChar << endl;
											errCount++;
										}
										
										inputChar = "";
										BEGIN(INITIAL);
										
									}
	YY_BREAK
case YY_STATE_EOF(ESCAPED_CHAR_STATE):
#line 662 "2005110.l"
{
										string outputChar = "'";
										outputChar += inputChar;
										
										logout << "Error at line# " << lineCount << ": UNFINISHED_CONST_CHAR " << outputChar << endl;
										errCount++;

										inputChar = "";
										BEGIN(INITIAL);
									}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 674 "2005110.l"
{
										string outputChar = "'";
										outputChar += inputChar;
										
										logout << "Error at line# " << lineCount << ": UNFINISHED_CONST_CHAR " << outputChar << endl;

										errCount++;

										inputChar = "";
										lineCount++;

										BEGIN(INITIAL);
									}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 688 "2005110.l"
{
										inputChar += yytext[0];
									}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 694 "2005110.l"
{
								BEGIN(STRING_STATE);
								start = lineCount;
							}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 699 "2005110.l"
{
								inputString += "\\";
								inputString += "\"";
							}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 705 "2005110.l"
{
								inputString += "\\";
								inputString += '\n';
								multiLineString = true;
								lineCount++;
							}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 713 "2005110.l"
{	
							string outputString = "\"";
							outputString += inputString;

							logout << "Error at line# " << lineCount << ": UNFINISHED_STRING " << outputString << endl;

							errCount++;
							lineCount++;

							inputString = "";
							multiLineString = false;

							BEGIN(INITIAL);	
						}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 729 "2005110.l"
{
								token += "\t";
								inputString += "\\";
								inputString += "t";
							}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 737 "2005110.l"
{
								token += "\a";
								inputString += "\\";
								inputString += "a";
							}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 744 "2005110.l"
{
								token += "\f";
								inputString += "\\";
								inputString += "f";
							}							
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 751 "2005110.l"
{
								token += "\r";
								inputString += "\\";
								inputString += "r";
							}					
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 758 "2005110.l"
{
								token += "\b";
								inputString += "\\";
								inputString += "b";
							}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 765 "2005110.l"
{
								token += "\v";
								inputString += "\\";
								inputString += "v";
							}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 772 "2005110.l"
{
								token += "\0";
								inputString += "\\";
								inputString += "0";
							}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 779 "2005110.l"
{
							string outputString = "\"";
							outputString += inputString;
							outputString += "\"";

							if(!multiLineString)
							{
								tokenout << "<SINGLE LINE STRING, " << token << ">" << endl;
								logout <<  "Line# " << lineCount << ": Token <SINGLE LINE STRING> Lexeme " << outputString << " found" << endl;

							}
							else
							{	
								tokenout << "<MULTI LINE STRING, " << token << ">" << endl;
								logout <<  "Line# " << start << ": Token <MULTI LINE STRING> Lexeme " << outputString << " found" << endl;

							}

							inputString = "";
							token = "";
							multiLineString = false;
							BEGIN(INITIAL);
							
						}
	YY_BREAK
case YY_STATE_EOF(STRING_STATE):
#line 806 "2005110.l"
{
							string outputString = "\"";
							outputString += inputString;

							logout << "Error at line# " << lineCount << ": UNFINISHED_STRING " << outputString << endl;

							errCount++;

							multiLineString = false;
							inputString = "";
							BEGIN(INITIAL);
						}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 821 "2005110.l"
{
							inputString += yytext;
							token += yytext;
						}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 829 "2005110.l"
{
										BEGIN(SINGLE_COMMENT_STATE);
										inputString += "//";
										start = lineCount ;
									}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 835 "2005110.l"
{
										inputString += "\\";
										inputString += '\n';
										lineCount++;

										multiLineString = true;

									}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 845 "2005110.l"
{
										if(!multiLineString)
										{
											logout <<  "Line# " << start << ": Token <SINGLE LINE COMMENT> Lexeme " << inputString << " found" << endl;
										}
										else
										{	
											logout <<  "Line# " << start << ": Token <SINGLE LINE COMMENT> Lexeme " << inputString << " found" << endl;
										}
										lineCount++;
										inputString = "";
										multiLineString = false;

										BEGIN(INITIAL);
									}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 862 "2005110.l"
{
										inputString += yytext;
									}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 869 "2005110.l"
{
										BEGIN(MULTI_LINE_COMMENT_STATE);
										inputString += "/";
										inputString += "*";
										start = lineCount;
									}
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 876 "2005110.l"
{
										inputString += "\n";
										lineCount++;
									}
	YY_BREAK
case YY_STATE_EOF(MULTI_LINE_COMMENT_STATE):
#line 881 "2005110.l"
{
										logout << "Error at line# " << lineCount << ": UNFINISHED_COMMENT " << inputString << endl;

										errCount++;

										inputString = "";
										BEGIN(INITIAL);
									}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 891 "2005110.l"
{
										
										inputString += "*";
										inputString += "/";

										logout <<  "Line# " << start << ": Token <MULTI LINE COMMENT> Lexeme " << inputString << " found" << endl;

										inputString = "";
										BEGIN(INITIAL);
									}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 903 "2005110.l"
{
										inputString += yytext[0];
									}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 908 "2005110.l"
{
			string input = yytext;
			logout << "Error at line# " << lineCount << ": UNRECOGNIZED_CHAR " << input << endl;

			errCount++;
		}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 918 "2005110.l"
ECHO;
	YY_BREAK
#line 1962 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_COMMENT_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 193 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 193 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 192);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 918 "2005110.l"


