#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from 2005110.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "2005110.y"

#include<iostream>
#include<cstdlib>
#include<cstring>
#include<cmath>
#include "2005110.h"

using namespace std;

int yyparse(void);
int yylex(void);

extern FILE* yyin;
extern ofstream logout;
extern int lineCount;
extern int errCount;
ofstream error_out;
ofstream parse_out;

extern SymbolTable table;


void yyerror(const char *s)
{
	//write your code
    //printf("In yyerror:");
}


void printParseTree(SymbolInfo* symbolInfo , int level)
{
	for(int i = 0; i < level ; i++)
	{
		parse_out << " ";
	}

	if(symbolInfo->getIsLeaf())
	{
		parse_out << symbolInfo->getType()<< " : " << symbolInfo->getName() << "	<Line: " << symbolInfo->getStartLine() << ">" << endl;
		return;
	}
	else{
		parse_out << symbolInfo->getParseTreeLine() << " 	" << "<Line: " << symbolInfo->getStartLine() << "-" << symbolInfo->getEndLine() << ">" << endl;
	}

	vector<SymbolInfo*>childList = symbolInfo->getChildList();

	for(int i = 0 ; i < childList.size() ; i++)
	{
		SymbolInfo* symbol = childList[i];
		printParseTree(symbol , level+1);
	}
	
}



#line 58 "2005110.y"
typedef union{
SymbolInfo* symbolInfo;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	ELSE	259
#define	FOR	260
#define	WHILE	261
#define	DO	262
#define	BREAK	263
#define	INT	264
#define	CHAR	265
#define	FLOAT	266
#define	DOUBLE	267
#define	VOID	268
#define	RETURN	269
#define	SWITCH	270
#define	CASE	271
#define	DEFAULT	272
#define	CONTINUE	273
#define	ID	274
#define	CONST_INT	275
#define	CONST_FLOAT	276
#define	ADDOP	277
#define	MULOP	278
#define	INCOP	279
#define	DECOP	280
#define	RELOP	281
#define	ASSIGNOP	282
#define	LOGICOP	283
#define	BITOP	284
#define	NOT	285
#define	LPAREN	286
#define	RPAREN	287
#define	LCURL	288
#define	RCURL	289
#define	LSQUARE	290
#define	RSQUARE	291
#define	COMMA	292
#define	SEMICOLON	293
#define	PRINTLN	294


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int ELSE;
static const int FOR;
static const int WHILE;
static const int DO;
static const int BREAK;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int VOID;
static const int RETURN;
static const int SWITCH;
static const int CASE;
static const int DEFAULT;
static const int CONTINUE;
static const int ID;
static const int CONST_INT;
static const int CONST_FLOAT;
static const int ADDOP;
static const int MULOP;
static const int INCOP;
static const int DECOP;
static const int RELOP;
static const int ASSIGNOP;
static const int LOGICOP;
static const int BITOP;
static const int NOT;
static const int LPAREN;
static const int RPAREN;
static const int LCURL;
static const int RCURL;
static const int LSQUARE;
static const int RSQUARE;
static const int COMMA;
static const int SEMICOLON;
static const int PRINTLN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,ELSE=259
	,FOR=260
	,WHILE=261
	,DO=262
	,BREAK=263
	,INT=264
	,CHAR=265
	,FLOAT=266
	,DOUBLE=267
	,VOID=268
	,RETURN=269
	,SWITCH=270
	,CASE=271
	,DEFAULT=272
	,CONTINUE=273
	,ID=274
	,CONST_INT=275
	,CONST_FLOAT=276
	,ADDOP=277
	,MULOP=278
	,INCOP=279
	,DECOP=280
	,RELOP=281
	,ASSIGNOP=282
	,LOGICOP=283
	,BITOP=284
	,NOT=285
	,LPAREN=286
	,RPAREN=287
	,LCURL=288
	,RCURL=289
	,LSQUARE=290
	,RSQUARE=291
	,COMMA=292
	,SEMICOLON=293
	,PRINTLN=294


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::ELSE=259;
const int YY_parse_CLASS::FOR=260;
const int YY_parse_CLASS::WHILE=261;
const int YY_parse_CLASS::DO=262;
const int YY_parse_CLASS::BREAK=263;
const int YY_parse_CLASS::INT=264;
const int YY_parse_CLASS::CHAR=265;
const int YY_parse_CLASS::FLOAT=266;
const int YY_parse_CLASS::DOUBLE=267;
const int YY_parse_CLASS::VOID=268;
const int YY_parse_CLASS::RETURN=269;
const int YY_parse_CLASS::SWITCH=270;
const int YY_parse_CLASS::CASE=271;
const int YY_parse_CLASS::DEFAULT=272;
const int YY_parse_CLASS::CONTINUE=273;
const int YY_parse_CLASS::ID=274;
const int YY_parse_CLASS::CONST_INT=275;
const int YY_parse_CLASS::CONST_FLOAT=276;
const int YY_parse_CLASS::ADDOP=277;
const int YY_parse_CLASS::MULOP=278;
const int YY_parse_CLASS::INCOP=279;
const int YY_parse_CLASS::DECOP=280;
const int YY_parse_CLASS::RELOP=281;
const int YY_parse_CLASS::ASSIGNOP=282;
const int YY_parse_CLASS::LOGICOP=283;
const int YY_parse_CLASS::BITOP=284;
const int YY_parse_CLASS::NOT=285;
const int YY_parse_CLASS::LPAREN=286;
const int YY_parse_CLASS::RPAREN=287;
const int YY_parse_CLASS::LCURL=288;
const int YY_parse_CLASS::RCURL=289;
const int YY_parse_CLASS::LSQUARE=290;
const int YY_parse_CLASS::RSQUARE=291;
const int YY_parse_CLASS::COMMA=292;
const int YY_parse_CLASS::SEMICOLON=293;
const int YY_parse_CLASS::PRINTLN=294;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		118
#define	YYFLAG		-32768
#define	YYNTBASE	40

#define YYTRANSLATE(x) ((unsigned)(x) <= 294 ? yytranslate[x] : 63)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     9,    11,    13,    20,    26,    33,
    39,    44,    48,    51,    53,    57,    60,    64,    66,    68,
    70,    74,    81,    83,    88,    90,    93,    95,    97,    99,
   107,   113,   121,   127,   133,   137,   139,   142,   144,   149,
   151,   155,   157,   161,   163,   167,   169,   173,   175,   179,
   182,   185,   187,   189,   194,   198,   200,   202,   205,   208,
   210,   211,   215
};

static const short yyrhs[] = {    41,
     0,    41,    42,     0,    42,     0,    47,     0,    43,     0,
    44,     0,    48,    19,    31,    45,    32,    38,     0,    48,
    19,    31,    32,    38,     0,    48,    19,    31,    45,    32,
    46,     0,    48,    19,    31,    32,    46,     0,    45,    37,
    48,    19,     0,    45,    37,    48,     0,    48,    19,     0,
    48,     0,    33,    50,    34,     0,    33,    34,     0,    48,
    49,    38,     0,     9,     0,    11,     0,    13,     0,    49,
    37,    19,     0,    49,    37,    19,    35,    20,    36,     0,
    19,     0,    19,    35,    20,    36,     0,    51,     0,    50,
    51,     0,    47,     0,    52,     0,    46,     0,     5,    31,
    52,    52,    54,    32,    51,     0,     3,    31,    54,    32,
    51,     0,     3,    31,    54,    32,    51,     4,    51,     0,
     6,    31,    54,    32,    51,     0,    39,    31,    19,    32,
    38,     0,    14,    54,    38,     0,    38,     0,    54,    38,
     0,    19,     0,    19,    35,    54,    36,     0,    55,     0,
    53,    27,    55,     0,    56,     0,    56,    28,    56,     0,
    57,     0,    57,    26,    57,     0,    58,     0,    57,    22,
    58,     0,    59,     0,    58,    23,    59,     0,    22,    59,
     0,    30,    59,     0,    60,     0,    53,     0,    19,    31,
    61,    32,     0,    31,    54,    32,     0,    20,     0,    21,
     0,    53,    24,     0,    53,    25,     0,    62,     0,     0,
    62,    37,    55,     0,    55,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    80,   103,   119,   137,   152,   167,   185,   205,   227,   246,
   268,   286,   303,   319,   337,   356,   374,   395,   410,   425,
   443,   461,   482,   498,   520,   535,   554,   569,   584,   598,
   619,   637,   658,   676,   694,   713,   727,   746,   761,   782,
   796,   816,   830,   850,   865,   885,   899,   919,   933,   953,
   969,   984,  1001,  1016,  1034,  1051,  1066,  1081,  1097,  1116,
  1131,  1138,  1155
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","ELSE",
"FOR","WHILE","DO","BREAK","INT","CHAR","FLOAT","DOUBLE","VOID","RETURN","SWITCH",
"CASE","DEFAULT","CONTINUE","ID","CONST_INT","CONST_FLOAT","ADDOP","MULOP","INCOP",
"DECOP","RELOP","ASSIGNOP","LOGICOP","BITOP","NOT","LPAREN","RPAREN","LCURL",
"RCURL","LSQUARE","RSQUARE","COMMA","SEMICOLON","PRINTLN","start","program",
"unit","func_declaration","func_definition","parameter_list","compound_statement",
"var_declaration","type_specifier","declaration_list","statements","statement",
"expression_statement","variable","expression","logic_expression","rel_expression",
"simple_expression","term","unary_expression","factor","argument_list","arguments",
""
};
#endif

static const short yyr1[] = {     0,
    40,    41,    41,    42,    42,    42,    43,    43,    44,    44,
    45,    45,    45,    45,    46,    46,    47,    48,    48,    48,
    49,    49,    49,    49,    50,    50,    51,    51,    51,    51,
    51,    51,    51,    51,    51,    52,    52,    53,    53,    54,
    54,    55,    55,    56,    56,    57,    57,    58,    58,    59,
    59,    59,    60,    60,    60,    60,    60,    60,    60,    61,
    61,    62,    62
};

static const short yyr2[] = {     0,
     1,     2,     1,     1,     1,     1,     6,     5,     6,     5,
     4,     3,     2,     1,     3,     2,     3,     1,     1,     1,
     3,     6,     1,     4,     1,     2,     1,     1,     1,     7,
     5,     7,     5,     5,     3,     1,     2,     1,     4,     1,
     3,     1,     3,     1,     3,     1,     3,     1,     3,     2,
     2,     1,     1,     4,     3,     1,     1,     2,     2,     1,
     0,     3,     1
};

static const short yydefact[] = {     0,
    18,    19,    20,     1,     3,     5,     6,     4,     0,     2,
    23,     0,     0,     0,     0,    17,     0,     0,    14,     0,
    21,     0,     8,    10,     0,     0,    13,    24,     0,     0,
     0,     0,     0,    38,    56,    57,     0,     0,     0,    16,
    36,     0,    29,    27,     0,     0,    25,    28,    53,     0,
    40,    42,    44,    46,    48,    52,     7,     9,    12,     0,
     0,     0,     0,     0,    61,     0,    53,    50,    51,     0,
     0,    23,    15,    26,    58,    59,     0,    37,     0,     0,
     0,     0,    11,    22,     0,     0,     0,    35,    63,     0,
    60,     0,    55,     0,    41,    43,    47,    45,    49,     0,
     0,     0,    54,     0,    39,     0,    31,     0,    33,    62,
    34,     0,     0,    32,    30,     0,     0,     0
};

static const short yydefgoto[] = {   116,
     4,     5,     6,     7,    18,    43,    44,    45,    12,    46,
    47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
    90,    91
};

static const short yypact[] = {    26,
-32768,-32768,-32768,    26,-32768,-32768,-32768,-32768,    13,-32768,
    18,    25,     6,   -11,    15,-32768,   -22,   -10,    32,   -18,
    30,    70,-32768,-32768,    -9,    26,-32768,-32768,    49,    51,
    62,    63,    66,    19,-32768,-32768,    66,    66,    66,-32768,
-32768,    64,-32768,-32768,    61,   107,-32768,-32768,    17,    67,
-32768,    71,    -1,    75,-32768,-32768,-32768,-32768,    83,    78,
    66,    36,    66,    68,    66,    66,    53,-32768,-32768,    79,
    88,    80,-32768,-32768,-32768,-32768,    66,-32768,    66,    66,
    66,    66,-32768,-32768,    85,    36,    87,-32768,-32768,    90,
    86,    89,-32768,    92,-32768,-32768,    75,   108,-32768,   144,
    66,   144,-32768,    66,-32768,    93,   128,   101,-32768,-32768,
-32768,   144,   144,-32768,-32768,   134,   135,-32768
};

static const short yypgoto[] = {-32768,
-32768,   132,-32768,-32768,-32768,    -5,    60,    10,-32768,-32768,
   -41,   -60,   -34,   -33,   -64,    65,    58,    72,   -30,-32768,
-32768,-32768
};


#define	YYLAST		183


static const short yytable[] = {    64,
    89,    86,    67,    67,    74,    70,    68,    69,    20,     9,
    22,    24,    95,     9,     1,    23,     2,    28,     3,    58,
    80,    25,    19,    22,    81,   101,    26,    85,    57,    87,
    67,    11,    92,    21,     1,    59,     2,    17,     3,   110,
    75,    76,    67,    77,    67,    67,    67,    67,    13,    65,
    27,    99,    14,    66,    34,    35,    36,    37,   107,     8,
   109,    15,    16,     8,    29,    38,    39,   108,    60,    67,
   114,   115,    30,    41,    31,    32,    75,    76,     1,    72,
     2,    61,     3,    33,    34,    35,    36,    37,    34,    35,
    36,    37,    62,    63,    71,    38,    39,    82,    79,    38,
    39,    83,    22,    40,    78,    88,    94,    41,    42,    30,
    93,    31,    32,    84,    14,     1,   100,     2,   102,     3,
    33,   103,   104,   106,   105,    34,    35,    36,    37,    80,
   111,   112,   113,   117,   118,    10,    38,    39,    98,    22,
    73,     0,     0,    96,    41,    42,    30,     0,    31,    32,
     0,    97,     1,     0,     2,     0,     3,    33,     0,     0,
     0,     0,    34,    35,    36,    37,     0,     0,     0,     0,
     0,     0,     0,    38,    39,     0,    22,     0,     0,     0,
     0,    41,    42
};

static const short yycheck[] = {    33,
    65,    62,    37,    38,    46,    39,    37,    38,    20,     0,
    33,    17,    77,     4,     9,    38,    11,    36,    13,    25,
    22,    32,    13,    33,    26,    86,    37,    61,    38,    63,
    65,    19,    66,    19,     9,    26,    11,    32,    13,   104,
    24,    25,    77,    27,    79,    80,    81,    82,    31,    31,
    19,    82,    35,    35,    19,    20,    21,    22,   100,     0,
   102,    37,    38,     4,    35,    30,    31,   101,    20,   104,
   112,   113,     3,    38,     5,     6,    24,    25,     9,    19,
    11,    31,    13,    14,    19,    20,    21,    22,    19,    20,
    21,    22,    31,    31,    31,    30,    31,    23,    28,    30,
    31,    19,    33,    34,    38,    38,    19,    38,    39,     3,
    32,     5,     6,    36,    35,     9,    32,    11,    32,    13,
    14,    32,    37,    32,    36,    19,    20,    21,    22,    22,
    38,     4,    32,     0,     0,     4,    30,    31,    81,    33,
    34,    -1,    -1,    79,    38,    39,     3,    -1,     5,     6,
    -1,    80,     9,    -1,    11,    -1,    13,    14,    -1,    -1,
    -1,    -1,    19,    20,    21,    22,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    30,    31,    -1,    33,    -1,    -1,    -1,
    -1,    38,    39
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 81 "2005110.y"
{
		//write your code in this block in all the similar blocks below
		yyval.symbolInfo = new SymbolInfo("start" , yyvsp[0].symbolInfo->getType());
		
		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "start : program";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;
		logout << "Total Lines: " << lineCount << endl;
        logout << "Total Errors: " << errCount << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

		printParseTree(yyval.symbolInfo , 1);
		
	;
    break;}
case 2:
#line 104 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("program" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "program : program unit";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 3:
#line 120 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("program" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine  = "program : unit";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 4:
#line 138 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("unit" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "unit : var_declaration";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 5:
#line 153 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("unit" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "unit : func_declaration";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 6:
#line 168 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("unit" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "unit : func_definition";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 7:
#line 186 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("func_declaration" , yyvsp[-5].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-5].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "func_declaration : type_specifier ID LPAREN parameter_list RPAREN SEMICOLON";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-5].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 8:
#line 206 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("func_declaration" , yyvsp[-4].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-4].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "func_declaration : type_specifier ID LPAREN RPAREN SEMICOLON";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
		
    ;
    break;}
case 9:
#line 228 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("func_definition" , yyvsp[-5].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-5].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "func_definition : type_specifier ID LPAREN parameter_list RPAREN compound_statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-5].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
	;
    break;}
case 10:
#line 247 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("func_definition" , yyvsp[-4].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-4].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "func_definition : type_specifier ID LPAREN RPAREN compound_statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 11:
#line 269 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("parameter_list" , yyvsp[-3].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-3].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "parameter_list : parameter_list COMMA type_specifier ID";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "parameter_list  : parameter_list COMMA type_specifier ID" << endl;

		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 12:
#line 287 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("parameter_list" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "parameter_list : parameter_list COMMA type_specifier";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 13:
#line 304 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("parameter_list" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "parameter_list : type_specifier ID";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "parameter_list  : type_specifier ID" << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 14:
#line 320 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("parameter_list" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "parameter_list  : type_specifier";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 15:
#line 338 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("compound_statement" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "compound_statement : LCURL statements RCURL";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

		table.PrintAllScopeTable(parse_out);

	;
    break;}
case 16:
#line 357 "2005110.y"
{
        yyval.symbolInfo = new SymbolInfo("compound_statement" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "compound_statement : LCURL RCURL";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);     
    ;
    break;}
case 17:
#line 375 "2005110.y"
{

		yyval.symbolInfo = new SymbolInfo("var_declaration" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine =  "var_declaration : type_specifier declaration_list SEMICOLON";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 18:
#line 396 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("type_specifier" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "type_specifier	: INT";
		yyval.symbolInfo->setParseTreeLine("type_specifier : INT");
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 19:
#line 411 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("type_specifier" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "type_specifier : FLOAT";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "type_specifier	: FLOAT" << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 20:
#line 426 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("type_specifier" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "type_specifier : VOID";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "type_specifier	: VOID" << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 21:
#line 444 "2005110.y"
{

		yyval.symbolInfo = new SymbolInfo("declaration_list" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getEndLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "declaration_list : declaration_list COMMA ID";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 22:
#line 462 "2005110.y"
{

		yyval.symbolInfo = new SymbolInfo("declaration_list" , yyvsp[-5].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-5].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "declaration_list : declaration_list COMMA ID LSQUARE CONST_INT RSQUARE";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-5].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
			
    ;
    break;}
case 23:
#line 483 "2005110.y"
{
			
		yyval.symbolInfo = new SymbolInfo("declaration_list" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "declaration_list : ID";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 24:
#line 499 "2005110.y"
{

		yyval.symbolInfo = new SymbolInfo("declaration_list" , yyvsp[-3].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-3].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "declaration_list : ID LSQUARE CONST_INT RSQUARE";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 25:
#line 521 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statements" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statements : statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 26:
#line 536 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statements" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statements : statements statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 27:
#line 555 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : var_declaration";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 28:
#line 570 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : expression_statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 29:
#line 585 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : compound_statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
    ;
    break;}
case 30:
#line 599 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[-6].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-6].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : FOR LPAREN expression_statement expression_statement expression RPAREN statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-6].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-5].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 31:
#line 620 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[-4].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-4].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : IF LPAREN expression RPAREN statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
    ;
    break;}
case 32:
#line 638 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[-6].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-6].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : IF LPAREN expression RPAREN statement ELSE statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-6].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-5].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 33:
#line 659 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[-4].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-4].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : WHILE LPAREN expression RPAREN statement";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
    ;
    break;}
case 34:
#line 677 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[-4].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-4].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : PRINTLN LPAREN ID RPAREN SEMICOLON";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-4].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
    ;
    break;}
case 35:
#line 695 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("statement" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "statement : RETURN expression SEMICOLON";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
    ;
    break;}
case 36:
#line 714 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("expression_statement" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "expression_statement 	: SEMICOLON";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
	;
    break;}
case 37:
#line 728 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("expression_statement" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "expression_statement : expression SEMICOLON";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 38:
#line 747 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("variable" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "variable : ID";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 39:
#line 762 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("variable" , yyvsp[-3].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-3].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "variable : ID LSQUARE expression RSQUARE";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 40:
#line 783 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("expression" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "expression : logic_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "expression 	: logic_expression" << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
 	;
    break;}
case 41:
#line 797 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("expression" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "expression : variable ASSIGNOP logic_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "expression 	: variable ASSIGNOP logic_expression " << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 42:
#line 817 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("logic_expression" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "logic_expression : rel_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
	;
    break;}
case 43:
#line 831 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("logic_expression" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "logic_expression : rel_expression LOGICOP rel_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 44:
#line 851 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("rel_expression" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "rel_expression : simple_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "rel_expression	: simple_expression" << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 45:
#line 866 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("rel_expression" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[-2].symbolInfo->getEndLine());

		string parseTreeLine = "rel_expression : simple_expression RELOP simple_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "rel_expression	: simple_expression RELOP simple_expression" << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 46:
#line 886 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("simple_expression" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "simple_expression : term";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
	;
    break;}
case 47:
#line 900 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("simple_expression" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "simple_expression : simple_expression ADDOP term";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 48:
#line 920 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("term" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "term : unary_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "term :	unary_expression" << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
	;
    break;}
case 49:
#line 934 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("term" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "term : term MULOP unary_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "term :	term MULOP unary_expression" << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 50:
#line 954 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("unary_expression" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "unary_expression : ADDOP unary_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
		
	;
    break;}
case 51:
#line 970 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("unary_expression" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "unary_expression : NOT unary_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
    ;
    break;}
case 52:
#line 985 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("unary_expression" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "unary_expression : factor";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
    ;
    break;}
case 53:
#line 1002 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("factor" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "factor : variable";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "factor	: variable" << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 54:
#line 1017 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("factor" , yyvsp[-3].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-3].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "factor : ID LPAREN argument_list RPAREN";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-3].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 55:
#line 1035 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("factor" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "factor : LPAREN expression RPAREN";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "factor	: LPAREN expression RPAREN" << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
		
    ;
    break;}
case 56:
#line 1052 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("factor" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "factor : CONST_INT";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "factor	: CONST_INT " << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 57:
#line 1067 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("factor" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "factor : CONST_FLOAT";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << "factor	: CONST_FLOAT" << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 58:
#line 1082 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("factor" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[-1].symbolInfo->getEndLine());

		string parseTreeLine = "factor	: variable INCOP";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 59:
#line 1098 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("factor" , yyvsp[-1].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-1].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[-1].symbolInfo->getEndLine());

		string parseTreeLine = "factor	: variable DECOP";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

    ;
    break;}
case 60:
#line 1117 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("argument_list" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "argument_list : arguments";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
		
	;
    break;}
case 61:
#line 1132 "2005110.y"
{

	;
    break;}
case 62:
#line 1139 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("arguments" , yyvsp[-2].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[-2].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "arguments : arguments COMMA logic_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[-2].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[-1].symbolInfo);
		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);

	;
    break;}
case 63:
#line 1156 "2005110.y"
{
		yyval.symbolInfo = new SymbolInfo("arguments" , yyvsp[0].symbolInfo->getType());

		yyval.symbolInfo->setStartLine(yyvsp[0].symbolInfo->getStartLine());
		yyval.symbolInfo->setEndLine(yyvsp[0].symbolInfo->getEndLine());

		string parseTreeLine = "arguments : logic_expression";
		yyval.symbolInfo->setParseTreeLine(parseTreeLine);
		logout << parseTreeLine << endl;

		yyval.symbolInfo->addChild(yyvsp[0].symbolInfo);
		
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 1173 "2005110.y"



int main(int argc,char *argv[])
{
	FILE* fp = fopen(argv[1] , "r");

	if(fp == NULL)
	{
		printf("Cannot Open Input File");
		exit(1);
	}

	logout.open("log.txt");
    error_out.open("error.txt");
    parse_out.open("parse_tree.txt");
	

	yyin=fp;
	yyparse();
	
	
	return 0;
}

